steps:

  # 1. Download the REAL model from Cloud Storage
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - storage
      - cp
      - gs://graduation-project-505807-models/paper_fingerprint_hybrid_lbp_resnet50_final.keras
      - model/paper_fingerprint_hybrid_lbp_resnet50_final.keras

  # 2. Verify the REAL model
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "===== MODEL CHECK ====="
        ls -lh model/
        du -h model/paper_fingerprint_hybrid_lbp_resnet50_final.keras
        file model/paper_fingerprint_hybrid_lbp_resnet50_final.keras
        echo "======================="

  # 3. Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/hybrid-lbp-resnet50:$COMMIT_SHA
      - .

  # 4. Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/hybrid-lbp-resnet50:$COMMIT_SHA

  # 5. Deploy Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - hybrid-lbp-resnet50-git
      - --image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/hybrid-lbp-resnet50:$COMMIT_SHA
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - 4Gi
      - --cpu
      - "2"
      - --timeout
      - "300"

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/hybrid-lbp-resnet50:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY